### PR TITLE
fix: :bug: Log added to solve the missing information reported in #267

### PR DESCRIPTION
**Pull request by GeorgeLBS1**
## Description
Fix issue #267, now 

### Fix
Now it is possible to see all the details of any failure when using the defect-dojo module, either coming from the devsecops-engine-tools or from any error obtained as a response from the defect-dojo API.
image

## Checklist:

- [X] The pull request is complete according to the guide of [contributing](https://github.com/bancolombia/devsecops-engine-tools/blob/trunk/docs/CONTRIBUTING.md) of this project
- [X] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Gaviria9601** [comment]
@GeorgeLBS1 thanks with the input, we are checking the bug with the github action Build - sonarqube . When it is ready we will let you know to complete the PR.

**Comment by Gaviria9601** [comment]
@GeorgeLBS1 Please update your branch with our trunk to fix the error with the github action

**Comment by GeorgeLBS1** [comment]
@Gaviria9601 branch updated

**Review by Gaviria9601 — APPROVED** [review]
thanks 👍

**Pull request merged**
